### ISSUE TITLE
Mails without "To" header vanish when using LMTP delivery

### ISSUE THREAD

**Issue by spezifisch** [getmail6/getmail6#105]
Firstly, I looked it up because I had doubts but mails without a "To" header are actually valid mails.

From [RFC2821](https://www.ietf.org/rfc/rfc2821.txt):
> When RFC 822 format [7, 32] is being used, the mail data include the
>   memo header items such as Date, Subject, To, Cc, From.  Server SMTP
>   systems SHOULD NOT reject messages based on perceived defects in the
>   RFC 822 or MIME [12] message header or message body. 

The blackbox tests in `./test/prepare_test.sh` [actually use a mail](https://github.com/getmail6/getmail6/blob/43af856348ece1be3b895d793c805ceee68a8047/test/prepare_test.sh#L225) for testing which only has an envelope recipient but no To/From headers.

To reproduce this bug I used my https://github.com/getmail6/getmail6/compare/master...spezifisch:test-dockerfile branch which only has some docker configuration changes but the getmail6 code itself is the same as in the current getmail6/master branch. OS is Debian bullseye.

```console
 q@debian  ~/test  docker -v        
Docker version 20.10.12, build e91ed57
 q@debian  ~/test  docker-compose -v
docker-compose version 1.29.2, build unknown
 q@debian  ~/test  cat /etc/debian_version 
11.2
# starting clean
 q@debian  ~/test  docker ps -a               
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
 q@debian  ~/test  git clone https://github.com/spezifisch/getmail6 -b test-dockerfile
Cloning into 'getmail6'...
remote: Enumerating objects: 4717, done.
remote: Counting objects: 100% (488/488), done.
remote: Compressing objects: 100% (346/346), done.
remote: Total 4717 (delta 329), reused 273 (delta 142), pack-reused 4229
Receiving objects: 100% (4717/4717), 2.00 MiB | 5.07 MiB/s, done.
Resolving deltas: 100% (3234/3234), done.
 q@debian  ~/test  cd getmail6 
# run tests
 q@debian  ~/test/getmail6   test-dockerfile  make test3
cd test && ./prepare_test.sh 3
Cloning into '/tmp/mailserver'...
remote: Enumerating objects: 14631, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 14631 (delta 45), reused 48 (delta 17), pack-reused 14518
[...]
Creating volume "mailserver_maildata" with default driver
Creating volume "mailserver_mailstate" with default driver
Creating volume "mailserver_maillogs" with default driver
Building mailserver
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM ghcr.io/docker-mailserver/docker-mailserver:9.0.1
 ---> be3f88f2240d
Step 2/7 : RUN apt-get update && apt-get -y install         git         iputils-ping         make         nmap         procmail         python-pip         python3-pip     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 79d416b93dd2
Step 3/7 : RUN useradd -m -s /bin/bash getmail
 ---> Using cache
 ---> 1a34a45953e0
Step 4/7 : COPY entrypoint.sh /
 ---> Using cache
 ---> 9d4773b89fcd
Step 5/7 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 63ebe25d5e87
Step 6/7 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 938925eed988
Step 7/7 : CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
 ---> Using cache
 ---> eb1a80640b29
Successfully built eb1a80640b29
Successfully tagged docker-mailserver-getmail6test:latest
Creating mail.domain.tld ... done
     Name                    Command               State                                                                             Ports                                                                           
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mail.domain.tld   /entrypoint.sh supervisord ...   Up      110/tcp, 0.0.0.0:143->143/tcp,:::143->143/tcp, 0.0.0.0:25->25/tcp,:::25->25/tcp, 4190/tcp, 465/tcp, 0.0.0.0:587->587/tcp,:::587->587/tcp,                 
                                                           0.0.0.0:993->993/tcp,:::993->993/tcp, 995/tcp                                                                                                             
Skipping getmail6 as it is not installed.
Obtaining file:///tmp/docker-mailserver/getmail6
Installing collected packages: getmail6
  Running setup.py develop for getmail6
Successfully installed getmail6
cd /tmp/mailserver && test/bats/bin/bats test/test_getmail_with_docker_mailserver.bats
 - first (skipped: this test must come first to reliably identify when to run setup_file)
 ✓ checking ssl 
 ✓ checking ports 
 ✓ SimplePOP3Retriever, destination Maildir 
 ✓ SimplePOP3SSLRetriever, destination Maildir 
 ✓ SimpleIMAPRetriever, destination Maildir 
 ✓ SimpleIMAPSSLRetriever, destination Maildir 
 ✓ SimplePOP3Retriever, destination MDA_external (procmail), filter spamassassin clamav 
 ✓ SimplePOP3SSLRetriever, destination MDA_external (procmail), filter spamassassin clamav 
 ✓ SimpleIMAPRetriever, destination MDA_external (procmail), filter spamassassin clamav 
 ✓ SimpleIMAPSSLRetriever, destination MDA_external (procmail), filter spamassassin clamav 
 ✓ BrokenUIDLPOP3Retriever, config test 
 ✓ BrokenUIDLPOP3SSLRetriever, config test 
 ✓ SimpleIMAPRetriever, config test 
 ✓ SimpleIMAPSSLRetriever, config test 
 ✓ MultidropPOP3Retriever 
 ✓ MultidropPOP3SSLRetriever 
 ✓ MultidropIMAPRetriever 
 ✓ MultidropIMAPSSLRetriever 
 ✓ MultidropPOP3Retriever, Multisorter 
 ✓ MultidropPOP3SSLRetriever, Multisorter 
 ✓ MultidropIMAPRetriever, Multisorter 
 ✓ MultidropIMAPSSLRetriever, Multisorter 
 ✓ MDA_lmtp 
 ✓ SimpleIMAPSSLRetriever, ALL, no delete 
 ✓ SimpleIMAPRetriever, UNSEEN, set seen 
 ✓ SimpleIMAPRetriever, UNSEEN, no unseen 
 ✓ SimpleIMAPSSLRetriever, ALL, delete 
 ✓ IMAP override via command line -s 
 ✓ getmail_mbox test 
 ✓ getmail_maildir test 
 ✓ getmail_fetch test 

32 tests, 0 failures, 1 skipped

 q@debian  ~/test/getmail6   test-dockerfile  docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS              PORTS                                                                                                                                                                                         NAMES
71848480a64e   docker-mailserver-getmail6test   "/entrypoint.sh supe…"   About a minute ago   Up About a minute   0.0.0.0:25->25/tcp, :::25->25/tcp, 110/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 465/tcp, 995/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 4190/tcp   mail.domain.tld
```

So tests work and the docker-mailserver test container is still running. Here is the getmail6 configuration:

```console
 q@debian  ~/test/getmail6   test-dockerfile  docker exec -it mail.domain.tld bash
# we need write access to /var/run/dovecot/lmtp for delivery
root@mail:/# usermod -a -G postfix getmail
root@mail:/# su getmail
getmail@mail:/$ cd

# create config
getmail@mail:~$ cat > /home/getmail/getmail <<EOF
> [retriever]
> type = SimpleIMAPRetriever
> server = localhost
> username = address@domain.tld
> port = 143
> password = test
> [destination]
> type = MDA_lmtp
> host = /var/run/dovecot/lmtp
> [options]
> read_all = True
> delete = True
> EOF

# clear leftover mail from test
getmail@mail:~$ getmail --rcfile=getmail --getmaildir=/home/getmail
getmail version 6.18.5
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPRetriever:address@domain.tld@localhost:143:
  msg 1/1 (918 bytes) delivered, deleted
  1 messages (918 bytes) retrieved, 0 skipped

# inbox is now empty
getmail@mail:~$ getmail --rcfile=getmail --getmaildir=/home/getmail
getmail version 6.18.5
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPRetriever:address@domain.tld@localhost:143:
  0 messages (0 bytes) retrieved, 0 skipped
```

So this rcfile should connect to localhost using IMAP with the user `address@domain.tld`.

The fetched mails should get delivered using LMTP over the unix socket `/var/run/dovecot/lmtp` (which is the same server but it should still work). This configuration example is [given in the docs](https://github.com/getmail6/getmail6/blob/43af856348ece1be3b895d793c805ceee68a8047/docs/configuration.txt#L1014).

We can then send a test mail (notice the envelope recipient but no recipient in the headers):

```console
# send our mail with netcat
getmail@mail:~$ nc 0.0.0.0 25 << EOF
> HELO mail.localhost
> MAIL FROM: address@domain.tld
> RCPT TO: address@domain.tld
> DATA
> Subject: test
> This is the test text
> .
> QUIT
> EOF
220 mail.domain.tld ESMTP
250 mail.domain.tld
250 2.1.0 Ok
250 2.1.5 Ok
354 End data with <CR><LF>.<CR><LF>
250 2.0.0 Ok: queued as C4F0643B7F
221 2.0.0 Bye
getmail@mail:~$ exit
root@mail:/# find /var/mail/domain.tld/address/new 
/var/mail/domain.tld/address/new
/var/mail/domain.tld/address/new/1640883016.M138709P3472.mail,S=604,W=621
```

The test mail is now sitting in address@domain.tld's inbox. The mailserver inferred the `From` header from the envelope but no `To` header:

```console
root@mail:/# cat /var/mail/domain.tld/address/new/1640883016.M138709P3472.mail\,S\=604\,W\=621 
Return-Path: <address@domain.tld>
Delivered-To: address@domain.tld
Received: from mail.domain.tld
        by mail.domain.tld with LMTP
        id TQMyCEjjzWGQDQAAsBn91A
        (envelope-from <address@domain.tld>)
        for <address@domain.tld>; Thu, 30 Dec 2021 16:50:16 +0000
Received: from localhost (localhost [127.0.0.1])
        by mail.domain.tld (Postfix) with ESMTP id 1DFB543AF5
        for <address@domain.tld>; Thu, 30 Dec 2021 16:50:16 +0000 (UTC)
X-Virus-Scanned: Yes
Subject: test
Message-Id: <20211230165014.C4F0643B7F@mail.domain.tld>
Date: Thu, 30 Dec 2021 16:50:14 +0000 (UTC)
From: address@domain.tld

This is the test text
```

We fetch it using getmail6:

```console
root@mail:/# su getmail
getmail@mail:/$ cd
getmail@mail:~$ getmail --rcfile=getmail --getmaildir=/home/getmail
getmail version 6.18.5
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPRetriever:address@domain.tld@localhost:143:
  msg 1/1 (621 bytes) delivered, deleted
  1 messages (621 bytes) retrieved, 0 skipped
```

And it's gone:

```console
getmail@mail:~$ exit
# not in original inbox
root@mail:/# find /var/mail/domain.tld/address/new
/var/mail/domain.tld/address/new
root@mail:/# find /var/mail/domain.tld/address    
/var/mail/domain.tld/address
/var/mail/domain.tld/address/tmp
/var/mail/domain.tld/address/new
/var/mail/domain.tld/address/cur
/var/mail/domain.tld/address/dovecot.list.index.log
/var/mail/domain.tld/address/dovecot-uidvalidity.61cde221
/var/mail/domain.tld/address/dovecot.index
/var/mail/domain.tld/address/dovecot.index.cache
/var/mail/domain.tld/address/dovecot-uidvalidity
/var/mail/domain.tld/address/dovecot-uidlist
/var/mail/domain.tld/address/dovecot.index.log
root@mail:/# 
```

Dovecot's log messages show the LMTP session starting, the IMAP session starting and ending and LMTP session ending without any mail being delivered:

```text
Dec 30 16:51:32 mail dovecot: lmtp(3815): Connect from local
Dec 30 16:51:32 mail dovecot: imap-login: Login: user=<address@domain.tld>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=3817, secured, session=<DCDa3V/UBLd/AAAB>
Dec 30 16:51:32 mail dovecot: imap(address@domain.tld)<3817><DCDa3V/UBLd/AAAB>: Logged out in=190 out=2222 deleted=1 expunged=1 trashed=0 hdr_count=0 hdr_bytes=0 body_count=1 body_bytes=621
Dec 30 16:51:32 mail dovecot: lmtp(3815): Disconnect from local: Remote closed connection (state=READY)
```

**Comment by spezifisch** [comment]
I first assumed this issue would not be present when using the `fallback` parameter for `MDA_lmtp` but in fact the mail vanishes there, too.

Here is a test with the `fallback` parameter set, which should lead to the mail being delivered to `address@domain.tld` in case LMTP delivery to the intended recipient fails:

```console
getmail@mail:~$ cat > getmail <<EOF
> [retriever]
> type = SimpleIMAPRetriever
> server = localhost
> username = address@domain.tld
> port = 143
> password = test
> [destination]
> type = MDA_lmtp
> host = /var/run/dovecot/lmtp
> fallback = address@domain.tld
> [options]
> read_all = True
> delete = True
> EOF
getmail@mail:~$ nc 0.0.0.0 25 << EOF
> HELO mail.localhost
> MAIL FROM: address@domain.tld
> RCPT TO: address@domain.tld
> DATA
> Subject: test
> This is the test text
> .
> QUIT
> EOF
220 mail.domain.tld ESMTP
250 mail.domain.tld
250 2.1.0 Ok
250 2.1.5 Ok
354 End data with <CR><LF>.<CR><LF>
250 2.0.0 Ok: queued as 78BA043B87
221 2.0.0 Bye
getmail@mail:/$ exit
root@mail:/# find /var/mail/domain.tld/address/new/
/var/mail/domain.tld/address/new/
/var/mail/domain.tld/address/new/1640885191.M301922P13063.mail,S=604,W=621
root@mail:/# su getmail
getmail@mail:/$ cd
getmail@mail:~$ getmail --rcfile=getmail --getmaildir=/home/getmail
getmail version 6.18.5
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPRetriever:address@domain.tld@localhost:143:
  msg 1/1 (621 bytes) delivered, deleted
  1 messages (621 bytes) retrieved, 0 skipped
getmail@mail:~$ getmail --rcfile=getmail --getmaildir=/home/getmail
getmail version 6.18.5
Copyright (C) 1998-2021 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPRetriever:address@domain.tld@localhost:143:
  0 messages (0 bytes) retrieved, 0 skipped
getmail@mail:~$ exit
root@mail:/# find /var/mail/domain.tld/address/    
/var/mail/domain.tld/address/
/var/mail/domain.tld/address/tmp
/var/mail/domain.tld/address/new
/var/mail/domain.tld/address/cur
/var/mail/domain.tld/address/dovecot.list.index.log
/var/mail/domain.tld/address/dovecot-uidvalidity.61cde221
/var/mail/domain.tld/address/dovecot.index
/var/mail/domain.tld/address/dovecot.index.cache
/var/mail/domain.tld/address/dovecot-uidvalidity
/var/mail/domain.tld/address/dovecot-uidlist
/var/mail/domain.tld/address/dovecot.index.log
root@mail:/# 
```

Same here, the mail is gone.

Mailserver log:

```text
Dec 30 17:26:30 mail postfix/postscreen[13047]: CONNECT from [127.0.0.1]:45916 to [127.0.0.1]:25
Dec 30 17:26:30 mail postfix/postscreen[13047]: WHITELISTED [127.0.0.1]:45916
Dec 30 17:26:30 mail postfix/smtpd[13048]: connect from localhost[127.0.0.1]
Dec 30 17:26:30 mail opendmarc[214]: ignoring connection from localhost
Dec 30 17:26:30 mail postfix/smtpd[13048]: improper command pipelining after HELO from localhost[127.0.0.1]: MAIL FROM: address@domain.tld\nRCPT TO: address@domain.tld\nDATA\nSubject: test\nThis is the test text\n.
Dec 30 17:26:30 mail postfix/smtpd[13048]: 78BA043B87: client=localhost[127.0.0.1]
Dec 30 17:26:30 mail postfix/cleanup[13052]: 78BA043B87: message-id=<20211230172630.78BA043B87@mail.domain.tld>
Dec 30 17:26:30 mail opendkim[208]: 78BA043B87: localhost [127.0.0.1] not internal
Dec 30 17:26:30 mail opendkim[208]: 78BA043B87: not authenticated
Dec 30 17:26:30 mail opendkim[208]: 78BA043B87: no signature data
Dec 30 17:26:30 mail postfix/qmgr[923]: 78BA043B87: from=<address@domain.tld>, size=381, nrcpt=1 (queue active)
Dec 30 17:26:30 mail postfix/smtpd[13048]: disconnect from localhost[127.0.0.1] helo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Dec 30 17:26:30 mail amavis[926]: (00926-14) ESMTP :10024 /var/lib/amavis/tmp/amavis-20211230T164521-00926-BDbRFjyO: <address@domain.tld> -> <address@domain.tld> SIZE=381 Received: from mail.domain.tld ([127.0.0.1]) by localhost (mail.domain.tld [127.0.0.1]) (amavisd-new, port 10024) with ESMTP for <address@domain.tld>; Thu, 30 Dec 2021 17:26:30 +0000 (UTC)
Dec 30 17:26:30 mail amavis[926]: (00926-14) Checking: smPoHrd7Lski [127.0.0.1] <address@domain.tld> -> <address@domain.tld>
Dec 30 17:26:30 mail amavis[926]: (00926-14) p001 1 Content-Type: text/plain, 7bit, size: 22, SHA1 digest: e6b61926e62740e4b4b16c315c2a8593371cb948
Dec 30 17:26:30 mail amavis[13056]: (00926-14) SA info: util: setuid: ruid=112 euid=112 rgid=114 114 egid=114 114 
Dec 30 17:26:31 mail postfix/smtpd[13061]: connect from localhost[127.0.0.1]
Dec 30 17:26:31 mail postfix/smtpd[13061]: 45D7243B81: client=localhost[127.0.0.1]
Dec 30 17:26:31 mail postfix/cleanup[13052]: 45D7243B81: message-id=<20211230172630.78BA043B87@mail.domain.tld>
Dec 30 17:26:31 mail postfix/smtpd[13061]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Dec 30 17:26:31 mail postfix/qmgr[923]: 45D7243B81: from=<address@domain.tld>, size=399, nrcpt=1 (queue active)
Dec 30 17:26:31 mail amavis[926]: (00926-14) smPoHrd7Lski FWD from <address@domain.tld> -> <address@domain.tld>, BODY=7BIT 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 45D7243B81
Dec 30 17:26:31 mail amavis[926]: (00926-14) Passed CLEAN {RelayedInbound}, [127.0.0.1]:45916 <address@domain.tld> -> <address@domain.tld>, Queue-ID: 78BA043B87, Message-ID: <20211230172630.78BA043B87@mail.domain.tld>, mail_id: smPoHrd7Lski, Hits: 1.205, size: 168, queued_as: 45D7243B81, 784 ms
Dec 30 17:26:31 mail amavis[926]: (00926-14) TIMING-SA total 749 ms - parse: 0.42 (0.1%), extract_message_metadata: 1.06 (0.1%), get_uri_detail_list: 0.11 (0.0%), tests_pri_-1000: 0.97 (0.1%), tests_pri_-950: 0.31 (0.0%), tests_pri_-900: 0.33 (0.0%), tests_pri_-400: 0.25 (0.0%), tests_pri_0: 740 (98.8%), check_spf: 0.10 (0.0%), check_dkim_signature: 0.21 (0.0%), check_dkim_adsp: 158 (21.1%), poll_dns_idle: 156 (20.8%), check_razor2: 262 (35.0%), check_pyzor: 306 (40.9%), tests_pri_500: 1.50 (0.2%), get_report: 0.15 (0.0%)
Dec 30 17:26:31 mail postfix/smtp[13053]: 78BA043B87: to=<address@domain.tld>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.8, delays=0.01/0.01/0/0.78, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 45D7243B81)
Dec 30 17:26:31 mail postfix/qmgr[923]: 78BA043B87: removed
Dec 30 17:26:31 mail amavis[926]: (00926-14) size: 168, TIMING [total 787 ms] - SMTP greeting: 1.2 (0%)0, SMTP EHLO: 0.3 (0%)0, SMTP pre-MAIL: 0.3 (0%)0, SMTP MAIL: 0.5 (0%)0, SMTP pre-DATA-flush: 0.6 (0%)0, SMTP DATA: 0.4 (0%)0, check_init: 0.4 (0%)0, digest_hdr: 0.1 (0%)0, digest_body: 0.1 (0%)0, collect_info: 0.3 (0%)1, mime_decode: 2.8 (0%)1, get-file-type1: 9 (1%)2, parts_decode: 0.1 (0%)2, check_header: 0.1 (0%)2, AV-scan-1: 1.8 (0%)2, spam-wb-list: 0.3 (0%)2, SA msg read: 0.2 (0%)2, SA parse: 0.7 (0%)2, SA check: 748 (95%)97, decide_mail_destiny: 1.4 (0%)98, notif-quar: 0.1 (0%)98, fwd-connect: 8 (1%)99, fwd-mail-pip: 1.2 (0%)99, fwd-rcpt-pip: 0.1 (0%)99, fwd-data-chkpnt: 0.0 (0%)99, write-header: 0.1 (0%)99, fwd-data-contents: 0.0 (0%)99, fwd-end-chkpnt: 3.4 (0%)99, prepare-dsn: 0.7 (0%)99, report: 0.6 (0%)99, main_log_entry: 2.0 (0%)100, update_snmp: 1.0 (0%)100, SMTP pre-response: 0.1 (0%)100, SMTP response: 0.1 (0%)100, unlink-1-files: 0.8 (0%)100, rundown: 0.3 (0%)100
Dec 30 17:26:31 mail dovecot: lmtp(13063): Connect from local
Dec 30 17:26:31 mail dovecot: lmtp(address@domain.tld)<13063><iEfqEcfrzWEHMwAAsBn91A>: sieve: msgid=<20211230172630.78BA043B87@mail.domain.tld>: stored mail into mailbox 'INBOX'
Dec 30 17:26:31 mail dovecot: lmtp(13063): Disconnect from local: Client has quit the connection (state=READY)
Dec 30 17:26:31 mail postfix/lmtp[13062]: 45D7243B81: to=<address@domain.tld>, relay=mail.domain.tld[/var/run/dovecot/lmtp], delay=0.03, delays=0/0.01/0.01/0.02, dsn=2.0.0, status=sent (250 2.0.0 <address@domain.tld> iEfqEcfrzWEHMwAAsBn91A Saved)
Dec 30 17:26:31 mail postfix/qmgr[923]: 45D7243B81: removed

Dec 30 17:27:24 mail dovecot: lmtp(13063): Connect from local
Dec 30 17:27:24 mail dovecot: imap-login: Login: user=<address@domain.tld>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=13304, secured, session=<qD0bXmDUFrd/AAAB>
Dec 30 17:27:24 mail dovecot: imap(address@domain.tld)<13304><qD0bXmDUFrd/AAAB>: Logged out in=190 out=2222 deleted=1 expunged=1 trashed=0 hdr_count=0 hdr_bytes=0 body_count=1 body_bytes=621
Dec 30 17:27:24 mail dovecot: lmtp(13063): Disconnect from local: Remote closed connection (state=READY)
```

**Comment by rpuntaie** [comment]
Would you make a pull request?

**Comment by spezifisch** [comment]
The problem seems to be in the exception handling for `SMTPRecipientsRefused`: https://github.com/getmail6/getmail6/blob/8c1f34082260529f66bdc4c5f7d9f1b64cb2c2d2/getmailcore/destinations.py#L726

```python
    def __send(self, msg, sender, recipient, __retrying=False):
        try:
            rcpt = self.server.send_message(msg, sender, recipient)
[...]
        except smtplib.SMTPRecipientsRefused as err:
            rcpt = err.recipients
[...]
        return rcpt
```

The server returns status 501: "5.5.4 Invalid TO: Null path not allowed" when trying to deliver that mail and the exception is raised.

[Python's smtplib docs say](https://docs.python.org/3/library/smtplib.html#smtplib.SMTPRecipientsRefused):

> *exception smtplib.SMTPRecipientsRefused*
>
>    All recipient addresses refused. The errors for each recipient are accessible through the attribute `recipients`, which is a dictionary of exactly the same sort as SMTP.sendmail() returns.

The [relevant part of SMTP.sendmail()]( If this method does not raise an exception, it returns a dictionary, with one entry for each recipient that was refused. Each entry contains a tuple of the SMTP error code and the accompanying error message sent by the server.):

>  If this method does not raise an exception, it returns a dictionary, with one entry for each recipient that was refused. Each entry contains a tuple of the SMTP error code and the accompanying error message sent by the server.

Reading this I would assume that in the [mentioned exception](https://github.com/getmail6/getmail6/blob/8c1f34082260529f66bdc4c5f7d9f1b64cb2c2d2/getmailcore/destinations.py#L726) `err.recipients` is a dictionary that contains: `{'': (501, b'5.5.4 Invalid TO: Null path not allowed')}`. But it is *not*. It's empty.

I modified the exception handler for testing like this:

```python
        except smtplib.SMTPRecipientsRefused as err:
            self.log.info(f"recipients refused err={err} err.recipients={err.recipients}\n")
            rcpt = err.recipients
```

The result is:

```
recipients refused err={} err.recipients={}
  msg 1/1 (621 bytes) delivered, deleted
  1 messages (621 bytes) retrieved, 0 skipped
```

I'll leave it at that for now, because I really don't know what goes wrong here.
IMO before further investigation this class really needs some unit tests to make debugging easier.

**Comment by easrng** [comment]
I'm getting a similar (related?) error, though I'm not sure if it's coming from getmail6 or the server I'm delivering to.
```
Delivery error (LMTP error: SMTPDataError: (503, b'5.5.1 Missing RCPT TO.'))
  msg  3675/17607 (6589 bytes), delivery error (LMTP error: SMTPDataError: (503, b'5.5.1 Missing RCPT TO.'))
```

**Comment by ChrisTG742** [comment]
So that the vanishing of mails is fixed by @spezifisch's PR, I wonder if it really makes sense to try to send mails with no recipient via SMTP/LMTP? From my understanding is okay that the mail is rejected by the server if it's not clear where it actually belongs to.
Of course, one could discuss about extending the exception handling. But what for? If a mail does not contain a "To"-field for some reason, even though the RFC says it "should not be rejected", I still don't see how you would want to deliver something that has not "recipient label" on it?
Just my 2 cents.

**Comment by Remmy** [comment]
While a message might not have a To: header, it can still have an envelope
recipient. Think of a mail where all the recipients are Bcc:ed. This is totally
valid and should be delivered to the indicated envelope recipient.

**Comment by ChrisTG742** [comment]
As far as I understood the method "send_message" from smtplib, the recipient-list is only auto-generated if the "to_addr" is "None", maybe it's worth checking what the variable "recipient" actually carries in [line 736](https://github.com/getmail6/getmail6/blob/8c1f34082260529f66bdc4c5f7d9f1b64cb2c2d2/getmailcore/destinations.py#L736). If it's just empty but not "None", the inbuilt expansion of the recipient from the envelope will not work.

**Comment by L-U-T-i** [comment]
Don't forget we are on a receiving side, having absolutely no influence on the sender / senders client (if "None" is correctly added or not). In any case, it is not desired the messages we receive are just (quietly) vanishing.

I believe it would still be better to add "None" to a 'To' field if it is just empty (if there is no better way to provide a recipient to the smtplib, I don't know much about it) than to let the message just being lost / undelivered. Or?

**Comment by ChrisTG742** [comment]
@L-U-T-i this is the way it is implemented in the module "smtplib", which is part of the official Pyhon3 distribution. Hence we don't have any influence on how it works internally.
What could be done from my perspective, is to add something like:
`       recipient = self.conf.get('override', msg.recipient)
        if recipient == '':
                 recipient = None
        rcpt = self.__send(msg.content(), msg.sender, recipient)`
